name: PilatesFlowA2
values:
  - key: token
    secret: true
  - key: baseUrl
    value: http://localhost:3000/api
  - key: bookingId
    value: ''
  - key: targetClassId
    value: ''
  - key: sourceClassId
    value: ''
